### PR TITLE
Fix register defintions.

### LINKED ISSUE #28: register struct issues
Refer to this code inside the *.h file: 

`unsigned int get() { return (t_sb << 5) | (filter << 3) | spi3w_en;}`  

 `            unsigned int get() {
                return (osrs_t << 5) | (osrs_p << 3) | mode;
            }`

I'm sure the bit shift 3 for "filter" and "osrs_p" should be 2, otherwise, it will overlap the t_sb and osrs_t bits values.

### PR DESCRIPTION
**Pull request by herm**
Fixes #28.

With this patch the sensor finally matches the specs from the datasheet. Before the pressure measurement where much worse because wrong settings were selected.

### CODE REVIEW

**Comment by herm** [comment]
This pull request is open for almost one year. The changes are trivial. Is there anything holding back merging this fix?

**Comment by ladyada** [comment]
thanks! :)

**Comment by Ivoz** [comment]
Hi @herm , do you know if the same correction should be made in the BPM280 library?

https://github.com/adafruit/Adafruit_BMP280_Library/blob/ce8d87d3d2569f08ef284477bba1b9db49730f22/Adafruit_BMP280.h#L256-L272

**Comment by herm** [comment]
Yes, the BMP280 library contains the exact same bug.

**Pull request merged**
