### PR TITLE
changed private to protected

### PR DESCRIPTION
**Pull request by espHorst**
Changed the private methods and attributes to protected. This allows to inherit the class and to reuse all the existing protected methods.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by espHorst** [comment]
That was fast. Thanks!

**Comment by ladyada** [comment]
@espHorst sorry i merged too fast - travis is not passing, please add the documentation strings!
https://travis-ci.com/adafruit/Adafruit_BME280_Library/builds/106625130
i

**Comment by espHorst** [comment]
Hm. Travis seems to throw warnings because of missing documentation for all the members that are now protected. Maybe travis does not request documentation for private members? Now all 27 former private members are protected. I can try to add the documentation, but this will take some time as I have to do some reverse engineering.

**Comment by ladyada** [comment]
that's right protected are available. please submit another PR to undo this one or i can undo it, so that the builds don't break!

**Comment by ladyada** [comment]
hiya i reverted this change

**Comment by espHorst** [comment]
Thanks for reverting. I'm giving it a new try with all doc strings provided. I have created a new PR and I hope travis will work ...

**Pull request merged**
