### PR TITLE
Added library.json for PlatformIO

### PR DESCRIPTION
**Pull request by drzony**
Adding library.json for use with PlatformIO, it adds required dependencies when disabling auto dependency finder

### CODE REVIEW

**Comment by ladyada** [comment]
thanks! 
we wont merge as platform.io can use the arduino properties file just fine and makes maintenance easier :)

**Comment by drzony** [comment]
Unfortunatelly the above cannot be done using library.properties right now, somehow PlatformIO handles dependencies there differently.

**Comment by ladyada** [comment]
dependencies are listed in all our arduino libraries now 👍 https://github.com/adafruit/Adafruit_BME280_Library/blob/master/library.properties

**Comment by drzony** [comment]
Yes, I'm aware of that, but PlatformIO does not handle them when dependency finder is turned off. I'll try to create an issue in PlatformIO or stick to my fork

**Comment by ladyada** [comment]
yes please create an issue with platformio - thank u!

**Pull request closed without merging**
