### PR TITLE
Sign-extend Humidity Calibration H4/H5 data (Fixes #44)

### LINKED ISSUE #44: Parsing H4/H5 humidity calibration data
According to the datasheet, dig_H4 and dig_H5 are signed integers on 12 bits

The following code handles these as pure 16bits signed, which will never be negative...
https://github.com/adafruit/Adafruit_BME280_Library/blob/07c30892653baceda6a426a8f8f79cc22194c590/Adafruit_BME280.cpp#L454-L455

The datasheet is ambiguous as it refers to these 12 bits values as `signed short`, but the [BoschSensortec reference code](https://github.com/BoschSensortec/BME280_driver/blob/a50e719dedec9c08efc3c8a9708881dfc4940848/bme280.c#L1227-L1233) definitely handles the values as 12 bits signed integer -- the `(int8_t)`cast on the msb ensures the sign is propagated

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by ladyada** [comment]
hiya why'd ya need to double-cast? never seen it befoer :)

**Comment by dirkmueller** [comment]
the first (inner) cast is a sign conversion (treating the read value as signed 8bit integer). the outer cast is a small optimisation, it changes the bitwise | and << operation to operate on signed 16bits (because we only store signed 16 bit integer anyway) instead of a machine specific int promotion (typically 32/64bit) (which would be the default in C/C++). I can remove that outer cast, it would not matter, the inner cast is the actual change. just let me know, I'll update it then.

**Comment by ladyada** [comment]
oki thanks for the details  - we'll have to test on hardware

**Comment by ladyada** [comment]
thanx!

**Pull request merged**
