### PR TITLE
Put BME280 to sleep before changing configuration

### PR DESCRIPTION
**Pull request by jrussek**
As mentioned in https://github.com/adafruit/Adafruit_BME280_Library/issues/30

### CODE REVIEW

**Comment by ladyada** [comment]
hiya please revert the mode afterwards :)

**Comment by jrussek** [comment]
Hi @ladyada,
the mode gets set to whatever mode in the parameter to setSampling() in line 198 anyways :)

**Comment by ladyada** [comment]
oh right!

**Comment by jrussek** [comment]
cheers :)

**Comment by ladyada** [comment]
thank you!!!

**Pull request merged**
