### PR TITLE
Code cleanups

### LINKED ISSUE #44: Parsing H4/H5 humidity calibration data
According to the datasheet, dig_H4 and dig_H5 are signed integers on 12 bits

The following code handles these as pure 16bits signed, which will never be negative...
https://github.com/adafruit/Adafruit_BME280_Library/blob/07c30892653baceda6a426a8f8f79cc22194c590/Adafruit_BME280.cpp#L454-L455

The datasheet is ambiguous as it refers to these 12 bits values as `signed short`, but the [BoschSensortec reference code](https://github.com/BoschSensortec/BME280_driver/blob/a50e719dedec9c08efc3c8a9708881dfc4940848/bme280.c#L1227-L1233) definitely handles the values as 12 bits signed integer -- the `(int8_t)`cast on the msb ensures the sign is propagated

### PR DESCRIPTION
**Pull request by dirkmueller**
A set of refactorings (no behavior change) accumulated over time.

### CODE REVIEW

**Comment by ladyada** [comment]
hiya - thanks for the PR! for this one, why did you remove the struct?

**Comment by dirkmueller** [comment]
@ladyada I tried to explain that in the commit message. with that extra struct, we're adding one redirect to every access (which adds code) and we add alignment padding (which adds memory footprint). this PR reduces memory consumption by 15%.

**Comment by ladyada** [comment]
hiya, we love fixes! refactors tend to add unintended side effects - so this code will take a while before we can test and merge, if ever - the current code works well, and we end up having to revert a large number of PRs due to unintended side effects.

if you'd like to work on improving the libraries, we recommend opening an issue - we can tell you exactly what would be best for the library in its current state, and work on small PRs. 

thanx :)

**Comment by dirkmueller** [comment]
@ladyada thats okay, we ended up forking the library to be able to fix the problems with lower turnaround time. The code has been tested and is used in production already. if you look for fixes, there is #56 and #57  waiting for review .. I have more, but I like to do small, easy to understand PRs.

**Comment by caternuson** [comment]
Closing. Looks like this was resolved elsewhere in a fork?

**Pull request closed without merging**
