### PR TITLE
begin() fail gracefully

### PR DESCRIPTION
**Pull request by sellensr**
**Adafruit_BME280.cpp**

begin(void) will now try the 0x76 alternate I2C address if it fails on 0x77.

init() now sets _sensorID to the sensor ID retrieved from the chip. Variable was previous declared, but not used.

New function sensorID() returns the value of the sensor ID for diagnostics.

Should be no functional changes from existing code, except success independent of address wiring.

**BME280test.ino**

Provides more diagnostics in the event that bme.begin() fails

### CODE REVIEW

**Comment by sellensr** [comment]
This is prompted by watching some of my students struggle when they downloaded the wrong library for the chip they were trying to use. Similar changes would make sense in the BMP 280 and BME 680 libraries.

**Comment by sellensr** [comment]
The fail on the M4 build doesn't happen on my machine -- maybe a configuration issue?

**Comment by siddacious** [comment]
@sellensr the M4 build issue was due to a stale cache which I fixed however Doxygen is now complaining that the macro for the new address is not documented.

**Comment by sellensr** [comment]
Passes the documentation check now -- this Doxygen process is new to me. Does it generate a more readable document that is available somewhere?

**Comment by ladyada** [comment]
http://adafruit.github.io/Adafruit_BME280_Library/html/index.html

**Comment by sellensr** [comment]
Also https://adafruit.github.io/Adafruit_SSD1306/html/index.html now that I know the pattern, but I'm guessing this is a work in progress ;-)

**Review by hoffmannjan — APPROVED** [review]

**Comment by hoffmannjan** [comment]
tested on uno & m0 and works fine :)

**Pull request merged**
