### PR TITLE
Create library.json

### PR DESCRIPTION
**Pull request by jacobrussell**
For use with platformio

### CODE REVIEW

**Comment by ivankravets** [comment]
@jacobrussell please make PR to https://github.com/platformio/platformio-libmirror/tree/master/configs/adafruit

P.S: @ladyada doesn't have time for startups and @PlatformIO. See https://github.com/platformio/platformio/issues/499

**Comment by ladyada** [comment]
yes that would be awesome, thank you @ivankravets & @jacobrussell :)

**Comment by glynhudson** [comment]
It's already here! Should have done a PlatformIO lib search first :+1: 

https://github.com/platformio/platformio-libmirror/blob/master/configs/adafruit/arduino-bme280.json

http://platformio.org/lib/show/166/Adafruit_BME280

**Comment by ivankravets** [comment]
@glynhudson we are working on the big update for PlatformIO, named "PlatformIO 3.0". We will introduce support for all existing C/C++ manifests (ARM mbed `module.json`, Arduino `library.properties`, etc). This will allow us to create #1 library registry for embedded with hundred libraries. You won't need to create [library.json](http://docs.platformio.org/en/stable/librarymanager/config.html) manifest for the package/library/module if you are not going to control PlatformIO Build System. If you need to specify custom build flags, extra build option or even to take control from PlatformIO Library Builder, you can use `extraScript` for that.

Nevertheless, ~95% of exisiting Arduino libraries could be registered with PlatformIO Library Registry with existing `library.properties` manifest. If you need more professional control on the library, please use our `library.json` manifest.

**Comment by ivankravets** [comment]
Great news! [PlatformIO Library Registry](http://platformio.org/lib) supports 3-rd party manifests:
- PlatformIO `library.json`
- Arduino `library.properties`
- ARM mbed `module.json`

You can register these manifests using generic [platformio lib register](http://docs.platformio.org/en/latest/userguide/lib/cmd_register.html) command. Later, we will add separate Web page where users can submit any libraries online.

Currently, our registry contains more than 1000 different embedded libraries. Of course, new PlatformIO 3.0 and its Library Manager with a semantic support and multiple library storages should embedded development on the new levell.

**Pull request closed without merging**
